version: '3.8'
services:
  app:
    image: rinha:latest
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=adm
      - DB_PASSWORD=123456
      - DB_NAME=rinha
  db:
    image: postgres:16rc1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=adm
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rinha
