version: '3.8'
services:
  app:
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 0.5G
    image: rinha:latest
    build: .
    ports:
      - "9999:9999"
    depends_on:
      - db
      - cache
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=administrator
      - DB_PASSWORD=123456
      - DB_NAME=rinha
  db:
    deploy:
      resources:
        limits:
          cpus: '1.15'
          memory: 2G
    image: postgres:16rc1-alpine
    ports:
      - "5432:5432"
    command: postgres -c max_connections=20000
    environment:
      - POSTGRES_USER=administrator
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=rinha
  cache:
    hostname: cache
    image: redis:latest
    command: redis-server --save "" --appendonly no
    ports:
      - '6379:6379'
    deploy:
      resources:
        limits:
          cpus: '0.06'
          memory: '0.5GB'
